name: Deploy Rem 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: project/rem-docs
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - working-directory: ./project/rem-docs
      run: |
        npm i
        npm run build
        mkdir -p ../../page/rem
        cp -r dist/* ../../page/rem
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "page/rem/"
        target: "/root/"